# Generated by Django 5.1.3 on 2024-12-27 18:35

import devopspanel.core.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BearerToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CodeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Code Base Name')),
                ('url', models.URLField(verbose_name='Repository URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'CodeBase',
                'verbose_name_plural': 'CodeBases',
            },
        ),
        migrations.CreateModel(
            name='CodeBaseDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Dependency Name')),
                ('url', models.URLField(verbose_name='Dependency URL')),
            ],
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Environment Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
            ],
            options={
                'verbose_name': 'Environment',
                'verbose_name_plural': 'Environments',
            },
        ),
        migrations.CreateModel(
            name='ServiceButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('icon_choice', models.CharField(blank=True, max_length=100, verbose_name='Icon (choose)')),
                ('custom_icon', models.ImageField(blank=True, null=True, upload_to=devopspanel.core.models.user_directory_path, verbose_name="Icon (User's)")),
                ('dev_language', models.CharField(blank=True, choices=[('Python', 'Python'), ('Java', 'Java'), ('C++', 'C++'), ('C#', 'C#'), ('JavaScript', 'JavaScript'), ('Ruby', 'Ruby'), ('PHP', 'PHP'), ('Go', 'Go'), ('Swift', 'Swift'), ('Kotlin', 'Kotlin'), ('Perl', 'Perl'), ('Rust', 'Rust'), ('Scala', 'Scala'), ('Objective-C', 'Objective-C'), ('Dart', 'Dart'), ('TypeScript', 'TypeScript'), ('Elixir', 'Elixir'), ('Haskell', 'Haskell'), ('Lua', 'Lua'), ('Erlang', 'Erlang'), ('Matlab', 'Matlab'), ('SQL', 'SQL'), ('PL/SQL', 'PL/SQL'), ('T-SQL', 'T-SQL'), ('MySQL', 'MySQL'), ('PostgreSQL', 'PostgreSQL'), ('MongoDB', 'MongoDB'), ('SQLite', 'SQLite'), ('Redis', 'Redis'), ('Cassandra', 'Cassandra'), ('MariaDB', 'MariaDB'), ('Oracle', 'Oracle')], max_length=50, null=True, verbose_name='Development Language')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('port', models.PositiveIntegerField(blank=True, null=True, verbose_name='Port')),
                ('version', models.CharField(blank=True, max_length=50, null=True, verbose_name='Version')),
                ('location', models.CharField(choices=[('K8S', 'K8S'), ('VM-GCP', 'VM-GCP'), ('Bare-Metal', 'Bare-Metal'), ('Cloud-SQL', 'Cloud-SQL'), ('CloudFlare', 'CloudFlare')], default='VM-GCP', max_length=20, verbose_name='Location')),
                ('is_multi_link', models.BooleanField(default=False, verbose_name='Is Multi-Link')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
            ],
            options={
                'verbose_name': 'Service Button',
                'verbose_name_plural': 'Service Buttons',
            },
        ),
        migrations.CreateModel(
            name='ServiceButtonIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceButtonLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Link Name')),
                ('url', models.URLField(verbose_name='URL')),
                ('location', models.CharField(choices=[('K8S', 'K8S'), ('VM-GCP', 'VM-GCP'), ('Bare-Metal', 'Bare-Metal'), ('Cloud-SQL', 'Cloud-SQL'), ('CloudFlare', 'CloudFlare')], default='VM-GCP', max_length=20, verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Service Button Link',
                'verbose_name_plural': 'Service Button Links',
            },
        ),
        migrations.CreateModel(
            name='ServiceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Group Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='SubGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='SubGroup Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
            ],
            options={
                'verbose_name': 'SubGroup',
                'verbose_name_plural': 'SubGroups',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
    ]
