# Generated by Django 5.1.3 on 2024-12-27 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bearertoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='codebasedependency',
            name='code_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='core.codebase', verbose_name='Code Base'),
        ),
        migrations.AddField(
            model_name='codebasedependency',
            name='dependencies',
            field=models.ManyToManyField(blank=True, related_name='dependents', to='core.codebasedependency'),
        ),
        migrations.AddField(
            model_name='environment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_environments', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='servicebutton',
            name='code_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_buttons', to='core.codebase', verbose_name='Code Base'),
        ),
        migrations.AddField(
            model_name='servicebutton',
            name='connections',
            field=models.ManyToManyField(blank=True, related_name='connected_to', to='core.servicebutton', verbose_name='Connections'),
        ),
        migrations.AddField(
            model_name='servicebutton',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='servicebutton',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='core.environment', verbose_name='Environment'),
        ),
        migrations.AddField(
            model_name='servicebutton',
            name='executive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executive_buttons', to=settings.AUTH_USER_MODEL, verbose_name='Executive'),
        ),
        migrations.AddField(
            model_name='servicebuttonip',
            name='service_button',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ips', to='core.servicebutton', verbose_name='Service Button'),
        ),
        migrations.AddField(
            model_name='servicebuttonlink',
            name='service_button',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='core.servicebutton', verbose_name='Service Button'),
        ),
        migrations.AddField(
            model_name='servicegroup',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='servicegroup',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='core.environment', verbose_name='Environment'),
        ),
        migrations.AddField(
            model_name='servicebutton',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='buttons', to='core.servicegroup', verbose_name='Groups'),
        ),
        migrations.AddField(
            model_name='subgroup',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='subgroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgroups', to='core.servicegroup', verbose_name='Group'),
        ),
        migrations.AddField(
            model_name='servicebutton',
            name='subgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='core.subgroup', verbose_name='SubGroup'),
        ),
        migrations.AddField(
            model_name='servicebutton',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='service_buttons', to='core.tag'),
        ),
        migrations.AlterUniqueTogether(
            name='servicegroup',
            unique_together={('name', 'environment')},
        ),
        migrations.AlterUniqueTogether(
            name='servicebutton',
            unique_together={('name', 'environment')},
        ),
    ]
