# Generated by Django 5.1.3 on 2024-12-28 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bearertoken',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=10),
        ),
    ]
