# Generated by Django 5.1.3 on 2024-12-28 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_maintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('canceled', 'Canceled'), ('completed', 'Completed'), ('partially_completed', 'Partially Completed')], default='scheduled', max_length=20, verbose_name='Status'),
        ),
    ]
