#!/bin/bash

# Check if required environment variables are set
required_vars=(
  BUILD_TAG TLS_HOST INGRESS_HOST POSITRACE_CRT POSITRACE_KEY SECRET_KEY DEBUG ALLOWED_HOSTS DB_ENGINE
  DB_NAME DB_USER DB_PASSWORD DB_HOST DB_PORT SECURE_SSL_REDIRECT SESSION_COOKIE_SECURE CSRF_COOKIE_SECURE
  SECURE_HSTS_SECONDS SECURE_HSTS_INCLUDE_SUBDOMAINS SECURE_HSTS_PRELOAD SECURE_BROWSER_XSS_FILTER SECURE_CONTENT_TYPE_NOSNIFF
  APP_LOG_LEVEL CSRF_TRUSTED_ORIGINS STATIC_URL DJANGO_SETTINGS_MODULE DJANGO_ADMINS
)

for var in "${required_vars[@]}"; do
  if [ -z "${!var}" ]; then
    echo "Error: Environment variable $var is not set."
    exit 1
  fi
done

cat <<EOF >custom-values.yaml
appVersion: "${BUILD_TAG}"
ingress:
  tlsHost: "${TLS_HOST_NEW}"
  ingressHost: "${INGRESS_HOST_NEW}"
secret:
  tls:
    crt: "${POSITRACE_CRT}"
    key: "${POSITRACE_KEY}"

configs:
  APP_TAG: "${BUILD_TAG}"
  SECRET_KEY: "${SECRET_KEY}"
  DEBUG: "${DEBUG}"
  ALLOWED_HOSTS: "${ALLOWED_HOSTS}"
  DB_ENGINE: "${DB_ENGINE}"
  DB_NAME: "${DB_NAME}"
  DB_USER: "${DB_USER}"
  DB_PASSWORD: "${DB_PASSWORD}"
  DB_HOST: "${DB_HOST}"
  DB_PORT: "${DB_PORT}"
  SECURE_SSL_REDIRECT: "${SECURE_SSL_REDIRECT}"
  SESSION_COOKIE_SECURE: "${SESSION_COOKIE_SECURE}"
  CSRF_COOKIE_SECURE: "${CSRF_COOKIE_SECURE}"
  SECURE_HSTS_SECONDS: "${SECURE_HSTS_SECONDS}"
  SECURE_HSTS_INCLUDE_SUBDOMAINS: "${SECURE_HSTS_INCLUDE_SUBDOMAINS}"
  SECURE_HSTS_PRELOAD: "${SECURE_HSTS_PRELOAD}"
  SECURE_BROWSER_XSS_FILTER: "${SECURE_BROWSER_XSS_FILTER}"
  SECURE_CONTENT_TYPE_NOSNIFF: "${SECURE_CONTENT_TYPE_NOSNIFF}"
  APP_LOG_LEVEL: "${APP_LOG_LEVEL}"
  CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS}
  STATIC_URL: ${STATIC_URL}
  DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
  DJANGO_ADMINS: ${DJANGO_ADMINS}
EOF
